export const projectData = [
  {
    id: "01",
    departement: "Ain",
    chef_lieu: "Bourg-en-Bresse",
    region: "Rhône-Alpes ",
  },
  {
    id: "02",
    departement: "Aisne",
    chef_lieu: "Laon",
    region: "Picardie ",
  },
  {
    id: "03",
    departement: "Allier",
    chef_lieu: "Moulins",
    region: "Auvergne ",
  },
  {
    id: "04",
    departement: "Alpes de Haute-Provence",
    chef_lieu: "Digne-les-Bains",
    region: "Provence-Alpes-Côte d'Azur ",
  },
  {
    id: "05",
    departement: "Hautes-Alpes",
    chef_lieu: "Gap",
    region: "Provence-Alpes-Côte d'Azur ",
  },
  {
    id: "06",
    departement: "Alpes-Maritimes",
    chef_lieu: "Nice",
    region: "Provence-Alpes-Côte d'Azur ",
  },
  {
    id: "07",
    departement: "Ardêche",
    chef_lieu: "Privas",
    region: "Rhône-Alpes ",
  },
  {
    id: "08",
    departement: "Ardennes",
    chef_lieu: "Charleville-Mézières",
    region: "Champagne-Ardenne ",
  },
  {
    id: "09",
    departement: "Ariège",
    chef_lieu: "Foix",
    region: "Midi-Pyrénées ",
  },
  {
    id: "10",
    departement: "Aube",
    chef_lieu: "Troyes",
    region: "Champagne-Ardenne ",
  },
  {
    id: "11",
    departement: "Aude",
    chef_lieu: "Carcassonne",
    region: "Languedoc-Roussillon ",
  },
  {
    id: "12",
    departement: "Aveyron",
    chef_lieu: "Rodez",
    region: "Midi-Pyrénées ",
  },
  {
    id: "13",
    departement: "Bouches-du-Rhône",
    chef_lieu: "Marseille",
    region: "Provence-Alpes-Côte d'Azur ",
  },
  {
    id: "14",
    departement: "Calvados",
    chef_lieu: "Caen",
    region: "Basse-Normandie ",
  },
  {
    id: "15",
    departement: "Cantal",
    chef_lieu: "Aurillac",
    region: "Auvergne ",
  },
  {
    id: "16",
    departement: "Charente",
    chef_lieu: "Angoulême",
    region: "Poitou-Charentes ",
  },
  {
    id: "17",
    departement: "Charente-Maritime",
    chef_lieu: "La Rochelle",
    region: "Poitou-Charentes ",
  },
  {
    id: "18",
    departement: "Cher",
    chef_lieu: "Bourges",
    region: "Centre ",
  },
  {
    id: "19",
    departement: "Corrèze",
    chef_lieu: "Tulle",
    region: "Limousin ",
  },
  {
    id: "2A",
    departement: "Corse-du-Sud",
    chef_lieu: "Ajaccio",
    region: "Corse ",
  },
  {
    id: "2B",
    departement: "Haute-Corse",
    chef_lieu: "Bastia",
    region: "Corse ",
  },
  {
    id: "21",
    departement: "Côte-d'Or",
    chef_lieu: "Dijon",
    region: "Bourgogne ",
  },
  {
    id: "22",
    departement: "Côtes d'Armor",
    chef_lieu: "St-Brieuc",
    region: "Bretagne ",
  },
  {
    id: "23",
    departement: "Creuse",
    chef_lieu: "Guéret",
    region: "Limousin ",
  },
  {
    id: "24",
    departement: "Dordogne",
    chef_lieu: "Périgueux",
    region: "Aquitaine ",
  },
  {
    id: "25",
    departement: "Doubs",
    chef_lieu: "Besançon",
    region: "Franche-Comté ",
  },
  {
    id: "26",
    departement: "Drôme",
    chef_lieu: "Valence",
    region: "Rhône-Alpes ",
  },
  {
    id: "27",
    departement: "Eure",
    chef_lieu: "Évreux",
    region: "Haute-Normandie ",
  },
  {
    id: "28",
    departement: "Eure-et-Loir",
    chef_lieu: "Chartres",
    region: "Centre ",
  },
  {
    id: "29",
    departement: "Finistère",
    chef_lieu: "Quimper",
    region: "Bretagne ",
  },
  {
    id: "30",
    departement: "Gard",
    chef_lieu: "Nîmes",
    region: "Languedoc-Roussillon ",
  },
  {
    id: "31",
    departement: "Haute-Garonne",
    chef_lieu: "Toulouse",
    region: "Midi-Pyrénées ",
  },
  {
    id: "32",
    departement: "Gers",
    chef_lieu: "Auch",
    region: "Midi-Pyrénées ",
  },
  {
    id: "33",
    departement: "Gironde",
    chef_lieu: "Bordeaux",
    region: "Aquitaine ",
  },
  {
    id: "34",
    departement: "Hérault",
    chef_lieu: "Montpellier",
    region: "Languedoc-Roussillon ",
  },
  {
    id: "35",
    departement: "Île-et-Vilaine",
    chef_lieu: "Rennes",
    region: "Bretagne ",
  },
  {
    id: "36",
    departement: "Indre",
    chef_lieu: "Châteauroux",
    region: "Centre ",
  },
  {
    id: "37",
    departement: "Indre-et-Loire",
    chef_lieu: "Tours",
  },
  {
    id: "38",
    departement: "Isère",
    chef_lieu: "Grenoble",
  },
  {
    id: "39",
    departement: "Jura",
    chef_lieu: "Lons-le-Saunier",
  },
  {
    id: "40",
    departement: "Landes",
    chef_lieu: "Mont-de-Marsan",
  },
  {
    id: "41",
    departement: "Loir-et-Cher",
    chef_lieu: "Blois",
  },
  {
    id: "42",
    departement: "Loire",
    chef_lieu: "Saint-Étienne",
  },
  {
    id: "43",
    departement: "Haute-Loire",
    chef_lieu: "Le Puy-en-Velay",
  },
  {
    id: "44",
    departement: "Loire-Atlantique",
    chef_lieu: "Nantes",
  },
  {
    id: "45",
    departement: "Loiret",
    chef_lieu: "Orléans",
  },
  {
    id: "46",
    departement: "Lot",
    chef_lieu: "Cahors",
  },
  {
    id: "47",
    departement: "Lot-et-Garonne",
    chef_lieu: "Agen",
  },
  {
    id: "48",
    departement: "Lozère",
    chef_lieu: "Mende",
  },
  {
    id: "49",
    departement: "Maine-et-Loire",
    chef_lieu: "Angers",
  },
  {
    id: "50",
    departement: "Manche",
    chef_lieu: "Saint-Lô",
  },
  {
    id: "51",
    departement: "Marne",
    chef_lieu: "Châlons-en-Champagne",
  },
  {
    id: "52",
    departement: "Haute-Marne",
    chef_lieu: "Chaumont",
  },
  {
    id: "53",
    departement: "Mayenne",
    chef_lieu: "Laval",
  },
  {
    id: "54",
    departement: "Meurthe-et-Moselle",
    chef_lieu: "Nancy",
  },
  {
    id: "55",
    departement: "Meuse",
    chef_lieu: "Bar-le-Duc",
  },
  {
    id: "56",
    departement: "Morbihan",
    chef_lieu: "Vannes",
  },
  {
    id: "57",
    departement: "Moselle",
    chef_lieu: "Metz",
  },
  {
    id: "58",
    departement: "Nièvre",
    chef_lieu: "Nevers",
  },
  {
    id: "59",
    departement: "Nord",
    chef_lieu: "Lille",
  },
  {
    id: "60",
    departement: "Oise",
    chef_lieu: "Beauvais",
  },
  {
    id: "61",
    departement: "Orne",
    chef_lieu: "Alençon",
  },
  {
    id: "62",
    departement: "Pas-de-Calais",
    chef_lieu: "Arras",
  },
  {
    id: "63",
    departement: "Puy-de-Dôme",
    chef_lieu: "Clermont-Ferrand",
  },
  {
    id: "64",
    departement: "Pyrénées-Atlantiques",
    chef_lieu: "Pau",
  },
  {
    id: "65",
    departement: "Hautes-Pyrénées",
    chef_lieu: "Tarbes",
  },
  {
    id: "66",
    departement: "Pyrénées-Orientales",
    chef_lieu: "Perpignan",
  },
  {
    id: "67",
    departement: "Bas-Rhin",
    chef_lieu: "Strasbourg",
  },
  {
    id: "68",
    departement: "Haut-Rhin",
    chef_lieu: "Colmar",
  },
  {
    id: "69",
    departement: "Rhône",
    chef_lieu: "Lyon",
  },
  {
    id: "70",
    departement: "Haute-Saône",
    chef_lieu: "Vesoul",
  },
  {
    id: "71",
    departement: "Saône-et-Loire",
    chef_lieu: "Mâcon",
  },
  {
    id: "72",
    departement: "Sarthe",
    chef_lieu: "Le Mans",
  },
  {
    id: "73",
    departement: "Savoie",
    chef_lieu: "Chambéry",
  },
  {
    id: "74",
    departement: "Haute-Savoie",
    chef_lieu: "Annecy",
  },
  {
    id: "75",
    departement: "Paris",
    chef_lieu: "Paris",
  },
  {
    id: "76",
    departement: "Seine-Maritime",
    chef_lieu: "Rouen",
  },
  {
    id: "77",
    departement: "Seine-et-Marne",
    chef_lieu: "Melun",
  },
  {
    id: "78",
    departement: "Yvelines",
    chef_lieu: "Versailles",
  },
  {
    id: "79",
    departement: "Deux-Sèvres",
    chef_lieu: "Niort",
  },
  {
    id: "80",
    departement: "Somme",
    chef_lieu: "Amiens",
  },
  {
    id: "81",
    departement: "Tarn",
    chef_lieu: "Albi",
  },
  {
    id: "82",
    departement: "Tarn-et-Garonne",
    chef_lieu: "Montauban",
  },
  {
    id: "83",
    departement: "Var",
    chef_lieu: "Toulon",
  },
  {
    id: "84",
    departement: "Vaucluse",
    chef_lieu: "Avignon",
  },
  {
    id: "85",
    departement: "Vendée",
    chef_lieu: "La Roche-sur-Yon",
  },
  {
    id: "86",
    departement: "Vienne",
    chef_lieu: "Poitiers",
  },
  {
    id: "87",
    departement: "Haute-Vienne",
    chef_lieu: "Limoges",
  },
  {
    id: "88",
    departement: "Vosges",
    chef_lieu: "Épinal",
  },
  {
    id: "89",
    departement: "Yonne",
    chef_lieu: "Auxerre",
  },
  {
    id: "90",
    departement: "Territoire-de-Belfort",
    chef_lieu: "Belfort",
  },
  {
    id: "91",
    departement: "Essonne",
    chef_lieu: "Évry",
  },
  {
    id: "92",
    departement: "Hauts-de-Seine",
    chef_lieu: "Nanterre",
  },
  {
    id: "93",
    departement: "Seine-Saint-Denis",
    chef_lieu: "Bobigny",
  },
  {
    id: "94",
    departement: "Val-de-Marne",
    chef_lieu: "Créteil",
  },
  {
    id: "95",
    departement: "Val-d'Oise",
    chef_lieu: "Pontoise",
  },
];
